language: android
jdk:
  - oraclejdk8
sudo: required
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - .+
before_install:
- openssl aes-256-cbc -K $encrypted_9492eac0682c_key -iv $encrypted_9492eac0682c_iv
  -in app/ignore.xml.enc -out app/src/main/res-main/values/ignore.xml -d
- openssl aes-256-cbc -K $encrypted_83fcb329e442_key -iv $encrypted_83fcb329e442_iv
  -in app/google-services.json.enc -out app/google-services.json -d
- chmod +x gradlew
script:
- ./gradlew build jacocoTestReport
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
